server:
  port: 20200

eureka:
  client:
    service-url:
      defaultZone: http://kimd0.iptime.org:20210/eureka/  # 유레카 서버 주소
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

path:
  server:
    cloud:
      host: kimd0.iptime.org
      port: 20200
      url: http://kimd0.iptime.org:20200
    batch:
      host: kimd0.iptime.org
      port: 20260
      url: http://kimd0.iptime.org:20260
    file:
      host: kimd0.iptime.org
      port: 20270
      url: http://kimd0.iptime.org:20270
    socket:
      host: kimd0.iptime.org
      port: 20280
      url: http://kimd0.iptime.org:20280
    member:
      host: kimd0.iptime.org
      port: 20290
      url: http://kimd0.iptime.org:20290
  service:
    batch:
      host: kimd0.iptime.org
      port1: 20180
      port2: 20181
      port3: 20182
      url: http://kimd0.iptime.org:20180
    cocoin:
      host: kimd0.iptime.org
      port: 20190
      url: http://kimd0.iptime.org:20190

spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      port: 6379
      host: redis-20480
  session:
    store-type: redis

rootPath: C:\\
rootImagePath: C:\\image

database:
  datasource:
    pub:
      master:
        url: jdbc:mysql://mysql-20490:3306/REP?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://mysql-20490:3306/REP?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
    log:
      master:
        url: jdbc:mysql://mysql-20490:3306/LOG?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://mysql-20490:3306/LOG?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
    cocoin:
      master:
        url: jdbc:mysql://mysql-20490:3306/REP?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://mysql-20490:3306/REP?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
    mattermost:
      master:
        url: jdbc:mysql://mysql-20490:3306/CRAWLING?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://mysql-20490:3306/CRAWLING?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
    coin:
      master:
        url: jdbc:mysql://mysql-20490:3306/CRAWLING?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://mysql-20490:3306/CRAWLING?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000